import type { NextPage } from "next";
import Head from "next/head";

import HeaderNav from "../components/HeaderNav";
import ArticleSection from "../components/ArticleSection";
import TokenInfoList from "../components/TokenInfoList";
import SocialUrlList from "../components/SocialUrlList";
import SwapInput from "../components/SwapInput";
import Countdown from "../components/Countdown";
import ProgressBar from "../components/ProgressBar";
import NoticeBoard from "../components/NoticeBoard";

import style from "../styles/Home.module.scss";
import 'antd/dist/reset.css';

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>RainbowKit App</title>
        <meta
          content="Generated by @rainbow-me/create-rainbowkit"
          name="description"
        />
        <link href="/logo.png" rel="icon" />
      </Head>

      <div className={style.App}>
        <div className={style.container}>
          <header>
            <HeaderNav />
          </header>
          <main className={style.main_content}>
            <section className={style.page_content}>
              <div className={style.part_left}>
                <ArticleSection />
                <SocialUrlList />
                <TokenInfoList />
              </div>
              <div className={style.part_right}>
                <div className={style.part_right_top}>
                  <div className={style.row_icon}></div>
                  <Countdown />
                  <ProgressBar />
                </div>
                <div className={style.part_right_bottom}>
                  <SwapInput />
                  <NoticeBoard />
                </div>
              </div>
            </section>
          </main>
        </div>
      </div>
    </>
  );
};

export default Home;
