import type { NextPage } from "next";
import Head from "next/head";

import HeaderNav from "../components/HeaderNav";
import ArticleSection from "../components/ArticleSection";
import TokenInfoList from "../components/TokenInfoList";
import SocialUrlList from "../components/SocialUrlList";
import SwapInput from "../components/SwapInput";
import Countdown from "../components/Countdown";
import ProgressBar from "../components/ProgressBar";
import NoticeBoard from "../components/NoticeBoard";

import style from "../styles/Home.module.scss";
import "antd/dist/reset.css";
import { useEffect, useState } from "react";
import logo from "../assets/logo/logo2.png";
import active_logo from "../assets/logo/logo3.png";
import icon_bnb from "../assets/icon/BNB.svg";
import Image from "next/image";
import { COUNTDOWN } from "../constants";

const Home: NextPage = () => {
  // page load
  const [domLoaded, setDomLoaded] = useState(false);
  // countdown
  const [onFinish, setOnFinish] = useState(false);

  useEffect(() => {
    setDomLoaded(true);
    if (Date.now() >= COUNTDOWN.deadline) {
      setOnFinish(true);
    }
  }, []);

  return (
    <>
      <Head>
        <title>RainbowKit App</title>
        <meta
          content="Generated by @rainbow-me/create-rainbowkit"
          name="description"
        />
        <link href="/logo.png" rel="icon" />
      </Head>

      {domLoaded && (
        <div className={style.App}>
          <div className={style.container}>
            <header>
              <HeaderNav />
            </header>
            <main className={style.main_content}>
              <section className={style.page_content}>
                <div className={style.part_left}>
                  <ArticleSection />
                  <SocialUrlList />
                  <TokenInfoList />
                </div>
                <div className={style.part_right}>
                  <div className={style.part_right_top}>
                    <div className={style.row_icon}>
                      <Image src={logo} alt="logo" />
                      <Image src={icon_bnb} alt="icon_bnb" />
                    </div>
                    <div className={style.part_right_top_content}>
                      {onFinish ? (
                        <>
                          <div className={style.row_icon_active}>
                            <Image src={active_logo} alt="logo" />
                          </div>
                          <ProgressBar />
                        </>
                      ) : (
                        <>
                          <Countdown />
                          <ProgressBar />
                        </>
                      )}
                    </div>
                  </div>
                  <div className={style.part_right_bottom}>
                    <SwapInput />
                    <NoticeBoard />
                  </div>
                </div>
              </section>
            </main>
          </div>
        </div>
      )}
    </>
  );
};

export default Home;
